# Be sure to restart your server when you change the secret.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.

development:
  secret_key_base: ${SECRET_KEY_BASE}

test:
  secret_key_base: ${SECRET_KEY_BASE}

production:
  secret_key_base: ${SECRET_KEY_BASE}
